Models/ErrorViewModel.cs
namespace ProyectoWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Formulario.cs
namespace ProyectoWeb.Models
{
    public class Formulario
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Mensaje { get; set; }
        public Formulario()
        {
            
        }
    }
       
}

Controllers/FormulariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoWeb.Data;
using ProyectoWeb.Models;

namespace ProyectoWeb.Controllers
{
    public class FormulariosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FormulariosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Formularios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Formulario.ToListAsync());
        }

        // GET: Formularios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formulario = await _context.Formulario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (formulario == null)
            {
                return NotFound();
            }

            return View(formulario);
        }

        // GET: Formularios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Formularios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Email,Mensaje")] Formulario formulario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(formulario);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            return View("Index", "Home");
        }

        // GET: Formularios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formulario = await _context.Formulario.FindAsync(id);
            if (formulario == null)
            {
                return NotFound();
            }
            return View(formulario);
        }

        // POST: Formularios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Email,Mensaje")] Formulario formulario)
        {
            if (id != formulario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(formulario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FormularioExists(formulario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(formulario);
        }

        // GET: Formularios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formulario = await _context.Formulario
                .FirstOrDefaultAsync(m => m.Id == id);
            if (formulario == null)
            {
                return NotFound();
            }

            return View(formulario);
        }

        // POST: Formularios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var formulario = await _context.Formulario.FindAsync(id);
            if (formulario != null)
            {
                _context.Formulario.Remove(formulario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FormularioExists(int id)
        {
            return _context.Formulario.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoWeb.Models;
using System.Diagnostics;

namespace ProyectoWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Formularios/Create.cshtml
@model ProyectoWeb.Models.Formulario

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Formulario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mensaje" class="control-label"></label>
                <input asp-for="Mensaje" class="form-control" />
                <span asp-validation-for="Mensaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Formularios/Delete.cshtml
@model ProyectoWeb.Models.Formulario

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Formulario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mensaje)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mensaje)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Formularios/Details.cshtml
@model ProyectoWeb.Models.Formulario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Formulario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mensaje)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mensaje)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Formularios/Edit.cshtml
@model ProyectoWeb.Models.Formulario

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Formulario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mensaje" class="control-label"></label>
                <input asp-for="Mensaje" class="form-control" />
                <span asp-validation-for="Mensaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Formularios/Index.cshtml
@model IEnumerable<ProyectoWeb.Models.Formulario>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mensaje)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mensaje)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
<! -- Esta es la pagina home de esta aplicacion, en el folder llamado formulario se encuentra las views usadas para la bases de datos, el formulario tambien se puede crear en esta pagina en el footer--> 
<! -- Las imagenes de este folder se encuentran en "wwwroot/lib/imagenes/"-->

@{
    ViewData["Title"] = "Home Page";
}
@model ProyectoWeb.Models.Formulario
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Wittgenstein:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&family=Kode+Mono:wght@400..700&display=swap" rel="stylesheet">
<div class="headline0">
    <h1 class="display-2  text-center">Prueba de pagina web</h1>
    <div class="px-5">
    <h2 class="parrafo text-center">Esta es una pagina web basica unicamente hecha para cumplir los objetivos de la prueba.
        
    
        </h2>
    </div>
</div>
<br></>
    <div class="headline">
<div class="headline1">
    <div class="foto-container">

        <img src="./lib/imagenes/imagen1.png"  />
    </div>
   
    <div class="textcontainer">
        <h1 class="display-4 ">Titulo</h1>
            <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h2>
    </div>
   
</div>
<div class="headline1">
    
    <div class="textcontainer">
        <h1 class="display-4">Titulo</h1>
            <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h2>

    </div>
    <div class="foto-container">
        <img src="./lib/imagenes/imagen2.webp" />
    </div>
    </div>
</div>
<br />

    <div class="products-section">
<br></br>        <div class="product-display">
            <div class="products">                          
                <img class="product-image default" src="./lib/imagenes/imagen3.png" />
            <img class="product-image hover" src="./lib/imagenes/imagen4.jpg" />
                <h3>Producto</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing eli</p>
            </div>
        <div class="products">
            <img class="product-image default" src="./lib/imagenes/imagen3.png" />
            <img class="product-image hover" src="./lib/imagenes/imagen4.jpg" />
            <h3>Producto</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing eli</p>
        </div>
        <div class="products">
            <img class="product-image default" src="./lib/imagenes/imagen3.png" />
            <img class="product-image hover" src="./lib/imagenes/imagen4.jpg" />
            <h3>Producto</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing eli</p>
        </div>
        
        <div class="products">
            <img class="product-image default" src="./lib/imagenes/imagen3.png" />
            <img class="product-image hover" src="./lib/imagenes/imagen4.jpg" />
            <h3>Producto</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
        <div class="products">
            <img class="product-image default" src="./lib/imagenes/imagen3.png" />
            <img class="product-image hover" src="./lib/imagenes/imagen4.jpg" />
            <h3>Producto</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
        </div>
        <div class="products">
            <img class="product-image default" src="./lib/imagenes/imagen3.png" />
            <img class="product-image hover" src="./lib/imagenes/imagen4.jpg" />
            <h3>Producto</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing eli</p>
        </div>
    </div><br />
    </div>



<footer class="footer-custom"><div class="contenedor-footer">
    <div class="align-self-center ">
        <h1>Contactanos:</h1>
        <br />
        <p>Email: ejemplo@ejemplo.com</p>
        <p>Telefono: (123) 456-7890</p>
    </div>
    <div class="separador"> </div>
    <div class="align-self-lg-end">
            <! -- Este es el formulario, por el momento solo valida que sea existente los datos correspodientes-->
            <h1> Formulario de contacto:</h1>
        <form asp-action="Create" asp-controller="Formularios">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label">Nombre:</label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email:</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mensaje" class="control-label">Mensaje:</label>
                <input asp-for="Mensaje" class="form-control" />
                <span asp-validation-for="Mensaje" class="text-danger"></span>
            </div>
            <div class="form-group text-center">
                <br>
                    <input type="submit" value="Crear" class="btn botones " />
                </div>
        
        </form>
        </div>
    </div>
   
</footer>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="headercolor navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-0">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item align-self-center">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item align-self-center">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Formularios" asp-action="Index">DB</a>
                        </li>
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    
        <main role="main" class="">
            @RenderBody()
        </main>
   
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>